#!/usr/bin/env ruby

$:.unshift(File.join(File.dirname(__FILE__), 'lib'))

require 'json'
require 'listyswarm'

filename = ARGV[0]

def usage
  <<-TXT
    Usage: #{$0} <config.json>
  TXT
end

unless filename
  print usage
  exit(1)
end

def deep_symbolize_keys(hash)
  {}.tap do |result|
    hash.each do |key, val|
      result[key.to_sym] = val.is_a?(Hash) ? deep_symbolize_keys(val) : val
    end
  end
end

config = deep_symbolize_keys(JSON.parse(File.read(filename)))

Universe.new(config).start
