#!/usr/bin/env ruby

$:.unshift(File.join(File.dirname(__FILE__), 'lib'))

require 'json'

# Require all nested files
Dir.glob('./lib/*.rb').each do |filename|
  require filename
end

filename = ARGV[0]

def usage
  <<-TXT
    Usage: #{$0} <config.json>
  TXT
end

unless filename
  print usage
  exit(1)
end

config = JSON.parse(File.read(filename)).inject({}) do |config, (key, val)|
  config[key.to_sym] = val
  config
end

Universe.new(config).start
